(
    MAIN_MENU_SELECT,
    ACCOUNT_CREATE,
    ACCOUNT_OPEN,
    ACCOUNT_MENU_SELECT,
    ACCOUNT_SET_LIMIT,
    ACCOUNT_SET_BALANCE,
    TRANSACTION_SET_AMOUNT,
    TRANSACTION_SET_DATE,
    TRANSACTION_SET_COMMENT,
    TRANSACTIONS_INDEX,
    TRANSACTION_REMOVE_LIST,
    TRANSACTION_REMOVE,
) = range(12)