# Generated by Django 5.1.1 on 2024-10-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram_id', models.IntegerField(unique=True)),
                ('username', models.TextField()),
                ('locale', models.TextField(null=True)),
            ],
        ),
    ]
