# Generated by Django 5.1.1 on 2024-10-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_account_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
