# Generated by Django 5.1.1 on 2024-10-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_rename_created_at_transaction_evaluated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='evaluated_at',
            field=models.DateTimeField(),
        ),
    ]
